### ISSUE TITLE
Using spring-security-oauth2 with Tencent QQ

### ISSUE THREAD

**Issue by ChinaSilence** [spring-projects/spring-security-oauth#1000]
my config:
```
qq:
  client:
    clientId: 101386962
    clientSecret: 2a0f820407df400b84a854d054be8b6a
    accessTokenUri: https://graph.qq.com/oauth2.0/token
    userAuthorizationUri: https://graph.qq.com/oauth2.0/authorize
    clientAuthenticationScheme: query
  resource:
    userInfoUri: https://graph.qq.com/oauth2.0/me
```
I find that 'clientAuthenticationScheme: form' is ok with github and facebook, but it's wrong with QQ. After I read the document of QQ,  I find that 'accessTokenUri:https://graph.qq.com/oauth2.0/token' should use GET method to get response, if use POST, will get a wrong response. Is there a way to set the method? or just only support POST now?

Get access_token from QQ step(can only use GET method), for example:
```
curl https://graph.qq.com/oauth2.0/authorize?response_type=code&client_id=101386962&redirect_uri=http://www.ictgu.cn/login/qq&state=pre

curl https://graph.qq.com/oauth2.0/token?grant_type=authorization_code&client_id=101386962&client_secret=2a0f820407df400b84a854d054be8b6a&code=3FEF1F50422408002DB32CD1512E5448&redirect_uri=http://www.ictgu.cn/login/qq

curl https://graph.qq.com/oauth2.0/me?access_token=A3EF70FD90C3E8F2F9189AE9AC648EE9
```
thanks for your response
