### ISSUE TITLE
Configuring security.oauth2.client but NOT security.oauth2.resource

### ISSUE THREAD

**Issue by alvgarvilla** [spring-projects/spring-security-oauth#1207]
I have my resource server were I want to configure the _security.oauth2.client_ properties:

```
security:
  oauth2:
    client:
      clientId: my-service-id
      clientSecret: my-service-id-secret
      accessTokenUri: http://auth-server/uaa/oauth/token
      grant-type: client_credentials
      scope: server
```

But I do not want to use _security.oauth2.resource_ properties, neither tokenInfoUri/userInfoUri nor key-value. I want to use _JwtAccessTokenConverter.setSigningKey("my_key")_.

The problem is, if I define _security.oauth2.client_, _OAuth2AutoConfiguration_ will create the a bean of _ResourceServerProperties_, which will validate whether I have any of the _security.oauth2.resource_ properties set or not.

As I work arround, I am setting a dummy value for _security.oauth2.resource.user-info-uri_ just to pass the validation, but I am pretty sure there must be a better way. Thanks in advance!
