### ISSUE TITLE
Could not autowire OAuth2ClientContext in oauth2 client

### ISSUE THREAD

**Issue by gaurav2887** [spring-projects/spring-security-oauth#1275]
In oauth2 client , it's showing error for not able to resolve OAuth2ClientContext injection in the following code. Error: 'Could not autowire. There is more than one bean of OAuth2ClientContext Type'. Any solution?

```
@Bean
	public OAuth2RestOperations restTemplate(OAuth2ClientContext oauth2ClientContext) {
		return new OAuth2RestTemplate(resource(), oauth2ClientContext);
	}

```

**Comment by kanz76** [comment]
Try to first to autowire using the qualifier as follows

 @Autowired
    @Qualifier("oauth2ClientContext")
    OAuth2ClientContext oAuth2ClientContext;

**Comment by kanz76** [comment]
Try first to autowire using the qualifier as follows

@Autowired
@qualifier("oauth2ClientContext")
OAuth2ClientContext oAuth2ClientContext;

**Comment by alcudiaMV** [comment]
@Autowired
    @Qualifier("oauth2ClientContext")
    OAuth2ClientContext oauth2ClientContext;

**Comment by steklopod** [comment]
A very strange thing. I hope this will be fixed.
Kotlin:
```kotlin
@Autowired @Qualifier("oauth2ClientContext") private val oauth2ClientContext: OAuth2ClientContext
```

**Comment by VCGDEV** [comment]
I was having same issue, it turns out that I forgot to add follow properties:
```
security:
  oauth2:
    client:
      clientId: bd1c0a783ccdd1c9b9e4
      clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
```

as specified in docs
[spring-security-oauth2](https://docs.spring.io/spring-security-oauth2-boot/docs/2.2.x-SNAPSHOT/reference/html/boot-features-security-custom-user-info-client.html)
