### ISSUE TITLE
invalid_redirect_uri_parameter exception

### ISSUE THREAD

**Issue by ayulit** [spring-projects/spring-security-oauth#1344]
### Summary

I'm using spring stack (Spring Boot 2.0.0.RELEASE) for creating a site that delegues user authentication/registration to Google via OAuth2. It is implemented as a few Spring Cloud microservices with a Zuul gateway running on port 8080.
```
  Google OAuth2
      |
      |
    Gateway   (:8080)
     /   \
    /     \
   /       \
Other      Client
```

I use Google as an OAuth2 server, and use **spring-security-oauth2** as a client. If all my cloud is deployed at localhost everything works fine. But if my microservices are deployed at **AWS Elastic Beanstalk**‎, OAuth login doesn't work.

### Actual Behavior

My application uses Google for registering and authenticating users. Currently I have a test environment running in AWS Elastic Beanstalk. When the Google's callback hits my application at AWS I get the following exception (from the logs):

```
org.springframework.security.oauth2.core.OAuth2AuthenticationException: [invalid_redirect_uri_parameter] 
	at org.springframework.security.oauth2.client.authentication.OAuth2LoginAuthenticationProvider.authenticate(OAuth2LoginAuthenticationProvider.java:117) ~[spring-security-oauth2-client-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:174) ~[spring-security-core-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
...
```
Taking a look at the sources I found that the issue seems to be in the following check in the `org.springframework.security.oauth2.client.authentication.OAuth2LoginAuthenticationProvider` class:

```
if (!authorizationResponse.getRedirectUri().equals(authorizationRequest.getRedirectUri())) {
    OAuth2Error oauth2Error = new OAuth2Error(INVALID_REDIRECT_URI_PARAMETER_ERROR_CODE);
    throw new OAuth2AuthenticationException(oauth2Error, oauth2Error.toString());
}
```
To check why this comparison is failing I checked the requests and responses using Chrome's developer tools. So, this is the call to Google:

`https://accounts.google.com/o/oauth2/v2/auth?response_type=code&client_id=[REMOVED]&scope=profile%20email&state=[REMOVED]&redirect_uri=https://[REMOVED]/auth/login/oauth2/code/google`

And this is Google's callback:
`https://[REMOVED]/auth/login/oauth2/code/google?state=[REMOVED]&code=[REMOVED]`

However, Spring Security is rejecting the user authentication because request and response redirect_uris are not matching.

I found the same problem on [StackOverflow](https://stackoverflow.com/questions/49765687/redirect-uri-using-http-instead-of-https) but with Facebook Oauth login, and it is still not solved yet.

### Expected Behavior

While running microservices at localhost everything is ok.

### Configuration

```
server:
  port: 5000
  servlet:
     contextPath: /auth
  use-forward-headers: true

spring:
  security:
    oauth2:
      resource:
        filter-order: 3
      client:
        registration:
          google:
            client-id:  [REMOVED]
            client-secret: [REMOVED]
            redirect-uri-template: ${AWS_CLOUD_URI:http://localhost:8080}/auth/login/oauth2/code/google
            scope: profile,email
```

### Version

- Spring Boot 2.0.0.RELEASE
- Spring Security OAuth2 Client 5.0.3.RELEASE
