### ISSUE TITLE
Use service discovery to configure OAuth server location

### ISSUE THREAD

**Issue by kmejka** [spring-projects/spring-security-oauth#1356]
Hi,
As the title says, I would like to configure the location of my oauth server in client apps using service discovery, preferably using consul.
Something like this:
```
security:
  oauth2:
    client:
      access-token-uri: http://<service-id>/oauth/token
```
I couldn't find this in any tutorial, usually it's just something like `http://localhost:8080`. Is it actually possible?
Thanks in advance
