### ISSUE TITLE
ZuulGateway 401 Unathorized / 403 forbidden Error for all request OAuth2 Spring Security

### ISSUE THREAD

**Issue by tYigitYilmaz** [spring-projects/spring-security-oauth#1553]
I am an inexperienced programming learner.

I have implemented Oauth2 security system, can't able to call through Zuul-Gateway my security methods.

Tried several methods which i have found but couldn't achieve the solution 

- security.basic.enable: false (not worked)
- `security.basic.enable: false` (not worked)
- `management.security.enabled: false.`(not worked - even not identified by property file)

yml file;
```
zuul:
  ignoredServices: '*'
  routes:
    application:
      path: /**
      serviceId: auth-server
      sensitive-headers: Cookie,Set-Cookie
      ignore-security-headers: false
      ignored-headers: cookie,set-cookie

security:
  basic:
    enabled: false

user:
  path: /user-service/**
  sensitiveHeaders:
  serviceId: user-service
```

Thank you!
