### ISSUE TITLE
Documentation states wrong configuration prefix.

### ISSUE THREAD

**Issue by wondee** [spring-projects/spring-security-oauth#1820]
### Summary

The Documenation states that the prefix for activating the `OAuth2ResourceServerConfiguration` is `spring.security.oauth.resource.*`, but in the `getMatchOutcome(..)` method the prefix is set like this `String prefix = "security.oauth2.resource.";`. 

### Configuration

Added `@EnableResourceServer` and add configuration like: 

```yaml

spring: 
  security:
    oauth2:
      resource:
        jwt:
          key-value: somekey

```

### Sample

See: https://docs.spring.io/spring-security-oauth2-boot/docs/current/reference/html/boot-features-security-oauth2-resource-server.html#oauth2-boot-resource-server-jwt-single-key
