### ISSUE TITLE
Empty scopes in AC when token endpoint responds with missing scope

### ISSUE THREAD

**Issue by gonzalad** [spring-projects/spring-security-oauth#828]
As of https://tools.ietf.org/html/rfc6749#section-5.1, scope is optional in token endpoint response.
If missing, then scopes should be identical to the scopes requested by the Client.

The problem is that Spring OAuth initializes a context with no scopes in this case.

I'm using Spring OAuth 2.0.10 and using this config : 

```
security:
  oauth2:
    client:
      clientId: TsEXSAJg5fSKPA
      clientSecret: yJhVPAgt1ZEnSNbGFbqx2g
      scope: openid refreshToken hello.say
      access-token-uri: http://localhost:9081/oidc/oauth2/token
      user-authorization-uri: http://localhost:9081/oidc/idp/authorize
      clientAuthenticationScheme: form
    resource:
      id: openid
      scope: openid refreshToken hello.say
      serviceId: ${PREFIX:}resource
      userInfoUri: http://localhost:9081/oidc/users/userinfo
```
