### ISSUE TITLE
Attempting to use a Load Balanced Rest Template

### ISSUE THREAD

**Issue by ChrisCooney** [spring-projects/spring-security-oauth#835]
We have a Spring Eureka server that we are using to register a variety of our services to. We want our application to be able to make requests to the service name, and not to the server itself. 

I have the following configuration:

````
/* The first attempt at getting this to work. However, doesn't seem to make a difference. */
zuul:
  routes:
    sis-auth:
      path: /**

security:
  oauth2:
    resource:
      tokenInfoUri: http://sis-auth/auth/oauth/check_token
    client:
      clientId: <id>
      clientSecret: <password>
````

However, I get a DNS name not found exception, because it can't find the DNS record for sis-auth. 

I attempted to solve this by defining a Rest Template bean that has the @LoadBalanced annotation associated with it, so that it is aware of Eureka and will allow routing through the service name, however diving into the code for the RemoteTokenServices I can see that the bean isn't injected; it is manually instanciated:

````java
public class RemoteTokenServices implements ResourceServerTokenServices {
    protected final Log logger = LogFactory.getLog(this.getClass());
    private RestOperations restTemplate = new RestTemplate();
````

This means that we are not able to override the behaviour of this. Should this be injected as a bean instead of created manually or is there a better approach to take?
