### ISSUE TITLE
Support for OpenID Connect Discovery

### ISSUE THREAD

**Issue by gonzalad** [spring-projects/spring-security-oauth#849]
Provide support for OpenID Connect Discovery (for ease of configuration of Application Clients and Resource Servers).

One goodie would be for discovery url to be discovered in lazy mode (no need for Authorization Server to be present in order to boot Spring Application - just access discovery uri once we really need to make the first call to Authorization Server).
# Sample Spring Configuration:

Instead of having this configuration for Application Client : 

```
security:
  oidc:
    client:
      expectedIssuer: sample.com
      keyUri: http://localhost:9080/oidc/jwk/keys
  oauth2:
    client:
      clientId: kMAv9qGdVf49Rw
      clientSecret: vO_DqZcF45WYarW_JhuPaw
      scope: openid refreshToken hello.say
      access-token-uri: http://localhost:9080/oidc/oauth2/token
      user-authorization-uri: http://localhost:9080/oidc/idp/authorize
```

Just add this configuration : 

```
security:
  oidc:
    client:
      expectedIssuer: sample.com
  oauth2:
    client:
      clientId: kMAv9qGdVf49Rw
      clientSecret: vO_DqZcF45WYarW_JhuPaw
      scope: openid refreshToken hello.say
      discovery-uri: http://localhost:9080/.well-known/openid-configuration
```

See http://openid.net/specs/openid-connect-discovery-1_0.html
This Url could also be used on Resource Server side (for pure OAuth clients, it seems to be pretty similar to https://tools.ietf.org/html/draft-jones-oauth-discovery-00).

Sample response from discovery url (as per specification http://openid.net/specs/openid-connect-discovery-1_0.html#rfc.section.4.2) : 

```
 HTTP/1.1 200 OK
  Content-Type: application/json

  {
   "issuer":
     "https://server.example.com",
   "authorization_endpoint":
     "https://server.example.com/connect/authorize",
   "token_endpoint":
     "https://server.example.com/connect/token",
   "token_endpoint_auth_methods_supported":
     ["client_secret_basic", "private_key_jwt"],
   "token_endpoint_auth_signing_alg_values_supported":
     ["RS256", "ES256"],
   "userinfo_endpoint":
     "https://server.example.com/connect/userinfo",
   "check_session_iframe":
     "https://server.example.com/connect/check_session",
   "end_session_endpoint":
     "https://server.example.com/connect/end_session",
   "jwks_uri":
     "https://server.example.com/jwks.json",
   "registration_endpoint":
     "https://server.example.com/connect/register",
   "scopes_supported":
     ["openid", "profile", "email", "address",
      "phone", "offline_access"],
   "response_types_supported":
     ["code", "code id_token", "id_token", "token id_token"],
   "acr_values_supported":
     ["urn:mace:incommon:iap:silver",
      "urn:mace:incommon:iap:bronze"],
   "subject_types_supported":
     ["public", "pairwise"],
   "userinfo_signing_alg_values_supported":
     ["RS256", "ES256", "HS256"],
   "userinfo_encryption_alg_values_supported":
     ["RSA1_5", "A128KW"],
   "userinfo_encryption_enc_values_supported":
     ["A128CBC-HS256", "A128GCM"],
   "id_token_signing_alg_values_supported":
     ["RS256", "ES256", "HS256"],
   "id_token_encryption_alg_values_supported":
     ["RSA1_5", "A128KW"],
   "id_token_encryption_enc_values_supported":
     ["A128CBC-HS256", "A128GCM"],
   "request_object_signing_alg_values_supported":
     ["none", "RS256", "ES256"],
   "display_values_supported":
     ["page", "popup"],
   "claim_types_supported":
     ["normal", "distributed"],
   "claims_supported":
     ["sub", "iss", "auth_time", "acr",
      "name", "given_name", "family_name", "nickname",
      "profile", "picture", "website",
      "email", "email_verified", "locale", "zoneinfo",
      "http://example.info/claims/groups"],
   "claims_parameter_supported":
     true,
   "service_documentation":
     "http://server.example.com/connect/service_documentation.html",
   "ui_locales_supported":
     ["en-US", "en-GB", "en-CA", "fr-FR", "fr-CA"]
  }
```
