### ISSUE TITLE
jdbc tokenStore example throws ClientAlreadyExistsException

### ISSUE THREAD

**Issue by dingquan** [spring-projects/spring-security-oauth#864]
I'm trying to use the demo code [here](https://github.com/spring-projects/spring-security-oauth/tree/master/tests/annotation/jdbc) to store oauth tokens in MySQL database.

It runs okey for the first time and I can get access token just fine by doing `POST localhost:8080/oauth/token`. But if I restart the server and try to get the token again. I got the exception saying client already exists:

`  "message": "Error creating bean with name 'scopedTarget.clientDetailsService' defined in class path resource [org/springframework/security/oauth2/config/annotation/configuration/ClientDetailsServiceConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.provider.ClientDetailsService]: Factory method 'clientDetailsService' threw exception; nested exception is org.springframework.security.oauth2.provider.ClientAlreadyExistsException: Client already exists: grubmarket",`

Configuration code:

	@Override
	public void configure(ClientDetailsServiceConfigurer clients) throws Exception {
		// @formatter:off
		clients.jdbc(dataSource).passwordEncoder(passwordEncoder)
			.withClient("***").secret("***")
				.authorizedGrantTypes("password", "authorization_code", "client_credentials",
						"refresh_token", "implicit")
				.authorities("ROLE_CLIENT", "ROLE_TRUSTED_CLIENT")
				.scopes("read", "write", "trust")
				.resourceIds("oauth2-resource")
				.accessTokenValiditySeconds(0);
		// @formatter:on
	}

application.yml:

```
security:
    oauth2:
        client:
            client-id: ***
            client-secret: ***
            scope: read,write
            authorized-grant-types: authorization_code,refresh_token,password,client_credentials
            auto-approve-scopes: openid
```

If I comment out the configuration code (the `withClient()...` part, then the code will run properly. Wonder whether there is a way to generate the oauth client details if not exist but skip it if it does so I don't need to uncomment the code to generate the oauth_client_details in the db then comment it out.
